issue06 first version
cube823/bigpicturelab-task pull request #8
Opened 2021-03-05 14:18 UTC by cube823

#6 

동 정보를 Content.jsx 페이지 뿐만 아니라 다른 jsx 파일에서도 사용하기 위해서 기존 useEffect 를 이용한 동 정보 받는 과정을 Content.jsx 파일에서 App.js 로 옮겼습니다. 해당 과정에서 들어가기 버튼을 누르면 각 상세 페이지로 이동하게 만들기 위해 react-router-dom 패키지를 사용했습니다. 상세페이지 렌더링은 DetailDong.jsx 파일에 구현했습니다.

동 정보가 담긴 서버 연결 에러 처리를 위해 AlertDialog.jsx 파일을, 잘못된 id 를 통한 상세페이지 접근 에러 처리를 위해 ErrorDetailDong.jsx 파일을 만들었습니다. 

리덕스를 제대로 사용할 줄 몰라 많은 시행착오를 겪었습니다. 잘못했거나 개선해야할 부분 말씀해주시면 정말 감사하겠습니다!

2021-03-08 12:48 UTC, byron1st requested changes
우선 업데이트 된 package.json 파일을 커밋에 포함시켜주기 바랍니다. gitignore에 혹시 실수로 package.json이 들어가있다면, 삭제해주세요. package.json 은 변경이 있을 시 반드시 커밋에 포함되어야 합니다. package.json이 없어서 제가 돌려보지 못했습니다.

2021-03-08 12:48 UTC, byron1st commented on src/App.js
> +    <Router>
Router 는 별도의 파일(`router.jsx` 등)로 분리해서 라우팅 관련 컴포넌트만 모아두는 것이 일반적입니다. 레이아웃 코드와 라우팅 코드가 뒤섞이면 나중에 '이 페이지가 어느 라우터로 뜬거지'라고 찾아야 할 때 고생할 수 있습니다.

2021-03-08 12:48 UTC, byron1st commented on src/App.js
> +                  <Route exact path={`/${dong.id}`} key={dong.id}>
이런 방식 보다는 라우팅 경로에 변수를 두고, 경로를 parsing 해서 dong ID 값을 추출하는 식으로 구성하는게 좋습니다. 이렇게 하면, Route 컴포넌트가 동 개수 만큼 쌓이게 되겠지요. https://reactrouter.com/web/example/url-params 항목을 참고하세요.

2021-03-08 12:48 UTC, byron1st commented on src/App.js
> +  }, [])
아마 밑에 36줄 코드 때문에 동 리스트 fetch 코드가 Content.jsx 에서 App.js 로 옮겨온 것 같습니다. 현재 상태에서는 둘다 나쁘진 않습니다만, 개인적으로 Content.jsx가 좀 더 좋습니다.

이유는, 만약 사용자가 `/dong-id` 를 직접 브라우저에 입력해서 들어올 경우, dong 리스트를 fetch 해오는 이 코드는 동작할 필요가 없음에도, 라우터 최상단 컴포넌트에 존재하는 바람에 항상 실행됩니다. 하지만 Content.jsx 로 이동하게 되면, `/` 경로를 정확히 들어오지 않는 한 저 API가 fetch 되지 않겠죠. 작지만 분명한 최적화 포인트 입니다. 혹시 이해가 잘 안되면 편하게 코멘트 달아주세요.

2021-03-08 12:52 UTC, byron1st commented
react-router-dom 패키지를 잘 찾아서 쓰신 것 잘하셨습니다. 전 개인적으로 라우팅에 다른 패키지를 씁니다만, react-router-dom이 더 메이저하고 좋습니다.

그리고 커밋에 파일이 좀 누락되어 있는 것 같습니다. package.json이 우선 업데이트 안 되어 있고요, redux 사용 코드도 제가 찾지 못했네요.

우선 이것들을 다 픽스하고, 머지 한 후 TypeScript 로 진행해보겠습니다.

2021-03-08 13:09 UTC, cube823 commented on src/App.js
> +    <Router>
package.json 을 우선 커밋했습니다. .gitignore 에 들어가지는 않고, 제가 실수록 누락했습니다ㅜ 죄송합니다! 피드백 주셔서 정말 감사합니다. 말씀해주신 다른 사항들은 내일까지 올리겠습니다! 늦은 시간에 죄송합니다!

2021-03-09 00:59 UTC, cube823 commented on src/App.js
> +    <Router>
router 를 위해 별도의 DongRouter.jsx 파일을 만들고 모두 옮겼습니다!

2021-03-09 01:00 UTC, cube823 commented on src/App.js
> +                  <Route exact path={`/${dong.id}`} key={dong.id}>
넵 고민했던 부분이었는데 짚어주셔서 정말 감사합니다! DongRouter.jsx 파일에 첨부해주신 링크 참조하여서 만들었습니다~!

2021-03-09 01:02 UTC, cube823 commented on src/App.js
> +  }, [])
넵 App.js 파일의 36줄 코드를 지움으로서 다시 동리스트 fetch 코드를 Content.jsx 파일로 옮겼습니다. 친절하게 설명해주셔서 정말 감사합니다..! 추가로 기존에 error 를 반환하던 .jsx 파일이 두 개 였는데 AlertDialog.jsx 파일로 합쳤습니다. 잘못했거나 개선해야하는 점 말씀해주시면 정말 감사합니다!!

2021-03-09 01:06 UTC, cube823 commented on src/App.js
> +  }, [])
추가로 redux 사용은 하지 않았습니다. 제가 잘몰라서 다른 식으로 구현하려 했다는 말을 잘못 표현했습니다ㅜ 감사합니다!

2021-03-09 08:34 UTC, cube823 commented on src/App.js
> +  }, [])
없는 id 호출시 에러와 빈 json 을 반환하게 코드를 수정해 commit 했습니다. 그러나 console 에 warning 이 뜨는 부분을 해결하지 못했습니다ㅜ 우선 올린 후 다시 확인하겠습니다. 감사합니다~!

2021-03-09 11:13 UTC, byron1st requested changes

2021-03-09 11:13 UTC, byron1st commented on src/components/DetailDong.jsx
> +    if (error) return error.status(400).json({})
`error.status(400).json({})` 코드가 이해하기 좀 어렵군요. Axios의 경우 `error`의 타입이 어떻게 되지요? `.status(400)`은 흡사 서버의 코드 같아보이는데, 여튼 이 부분이 좀 이해하기 어렵습니다.

대충 에러 상황을 연출해보니, `error`는 그냥 normal 한 `Error` 타입입니다. 이 부분에 대한 수정이 있어야 할 것으로 보입니다.

그리고 `errorMessage`는 함수 객체인데, 밑에 return 부분에서 그냥 삽입이 되어 "Functions are not valid as a React child." warning이 발생하고, 실제로 에러 상황에서도 동작하지 않습니다. `errorMessage`가 무언가 React 컴포넌트를 반환하는게 좋겠습니다.

2021-03-09 11:13 UTC, byron1st commented on src/components/DetailDong.jsx
> +      {detail()}
```js
<div>
  {error ? <AlertDialog /> : <TableContainer ...> ... </TableContainer>}
</div>
```

와 같이 사용하는게 일반적입니다. 함수 실행 구문을 return 코드에 잘 넣지는 않는데, 일단 코드의 가독성이 좀 떨어지고, `detail()`와 같이 함수로 넣을 바에는 아애 `<Detail />` 와 같이 별도의 리엑트 컴포넌트로 정의해서 삽입하는 편이 좋습니다.

2021-03-09 11:13 UTC, byron1st commented on src/components/AlertDialog.jsx
> +        <DialogTitle id="alert-dialog-title">{errorMessageFinder()}</DialogTitle>
`{error ? error.message : '400 Bad Request' }`와 같이 inline으로 처리해주는게 코드 가독성에 좋을 것 같네요.

2021-03-09 11:13 UTC, byron1st commented on src/components/DongRouter.jsx
> +  let { id } = useParams()
이 코드를 그냥 `DetailDong`에 포함시키고, `DetailDong` 컴포넌트를 `Route` 에서 직접 참조하는게 좋을 것 같네요. 코드를 읽는데 두세 단계를 거쳐서 읽지 않아도 되니, 가독성이 좋아질 것 같군요. 별도의 함수 정의가 없어도 되는 장점도 있구요.

2021-03-09 11:13 UTC, byron1st commented on src/components/Search.jsx
> +    return console.log(text)
`return` 은 불필요한 것 같습니다.

2021-03-09 11:18 UTC, byron1st commented on src/App.js
> +  }, [])
아 이 메세지를 먼저 보고 리뷰를 작성할 걸 그랬네요.

Warning은 return 파트의 `{errorMessage}` 때문입니다. `render` 함수의 return 부분에는 반드시 리엑트 컴포넌트만 위치해야 합니다. 근데 `errorMessage`는 함수 객체죠. `{detail()}`과 같이, 함수를 실행해서 반환한 결과가 리엑트 컴포넌트이면 괜찮지만, 함수 객체 자체를 그냥 넣었기 때문에 에러가 발생합니다. 이를 피하기 위해서는 명백히 리엑트 컴포넌트인 코드 (예: `<DetailDong />`) 만 return 파트에 넣는것이 좋습니다.

2021-03-09 11:59 UTC, cube823 commented on src/App.js
> +  }, [])
알려주셔서 정말 감사합니다 이해가 되었습니다! 적어주신대로 코드를 수정하였습니다 감사합니다!!

2021-03-09 12:08 UTC, cube823 commented on src/components/DetailDong.jsx
> +    if (error) return error.status(400).json({})
기존에 '400 Bad Request, {}'를 하드코딩 형식보다 status(400)으로 써보는 편이 낫지 않을까 하여 적었습니다.. DetailDong.jsx 파일에서 <AlertDialog /> 컴포넌트에 error property 를 주어 문제를 해결하는 방식으로 바꾸었습니다!

2021-03-09 12:10 UTC, cube823 commented on src/components/AlertDialog.jsx
> +        <DialogTitle id="alert-dialog-title">{errorMessageFinder()}</DialogTitle>
넵 짚어주셔서 감사합니다! 이 부분은 위에서 썼듯이 DetailDong.jsx 파일의 <AlertDialog /> 컴포넌트에 error property 를 주는 방식으로 해결하고자 했습니다!!

2021-03-09 12:11 UTC, cube823 commented on src/components/DongRouter.jsx
> +  let { id } = useParams()
넵 useParams hook 에 관한 이해가 부족하여 생긴 코드였습니다. 강의 영상 참조하여 수정했습니다. 감사합니다~!

2021-03-09 12:12 UTC, cube823 commented on src/components/Search.jsx
> +    return console.log(text)
넵 search 기능도 수행할 수 있으면 좋을 것 같아 이것저것 해보다가 잘 안 되어 원상태로 돌리는 과정에서 들어갔습니다.. 수정했습니다. 짚어주셔서 감사합니다!

2021-03-09 14:31 UTC, merged